version: '0.1.0'

index:
    name: vecquestions
    prefix: qst
    storage_type: json

fields:
    - name: question
      type: text
    - name: answer
      type: text
    - name: embedding
      type: vector
      attrs:
        dims: 384
        algorithm: flat
        distance_metric: cosine
        datatype: float32